# -*- restclient -*-

#
# Get all classes
GET http://localhost:3000/classes
#
# Restrict it to a single club
GET http://localhost:3000/classes?club=09
#
# Restrict it to a single class
GET http://localhost:3000/classes?name=62
#
# Combine it 
GET http://localhost:3000/classes?name=62&club=09
#
# Get by date
GET http://localhost:3000/classes?date=2019-07-02
#
# Get by hour
GET http://localhost:3000/classes?hour=09&date=2019-07-02
#
# Get by hour
GET http://localhost:3000/classes?hour=09
#
#  Get ClassTypes
GET http://localhost:3000/classtypes

#
# POST Analytics event
POST https://localhost:3000/analytics
Content-Type: application/json
    {
      "user": "105d011a-d1a1-4583-835c-7c8b87a74802", 
      "session": "270017c9-e544-47eb-93a9-b90f32c3248f", 
      "data": {"value": "01", "label": "Auckland City"},
      "action": "Selected Gym Filter"
    }